### ISSUE TITLE
Crash on 1.19.3

### ISSUE THREAD

**Issue by DrProid** [Roundaround/mc-fabric-villager-converting#4]
Recently trying to update my server to 1.19.3. Everything works on 1.19.2.

I confirmed that it was this mod by running isolation tests. Then forced the error by sticking a villager in a pen with a zombie.

It looks like a method (onKilledOther) in the zombie class has changed name or been deleted. This could also just be an issue with fabric API.

From the crash log:
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2022-12-12 12:43:49
Description: Ticking entity

java.lang.NoSuchMethodError: 'com.mojang.serialization.Dynamic net.minecraft.class_4136.method_19067(com.mojang.serialization.DynamicOps)'
	at net.minecraft.class_1642.handler$zgi000$onKilledOther(class_1642.java:708)
	at net.minecraft.class_1642.method_5874(class_1642.java)
	at net.minecraft.class_1309.method_6078(class_1309.java:1352)
	at net.minecraft.class_3988.method_6078(class_3988.java:203)
	at net.minecraft.class_1646.method_6078(class_1646.java:657)
	at net.minecraft.class_1309.method_5643(class_1309.java:1210)
	at net.minecraft.class_1308.method_6121(class_1308.java:1457)
	at net.minecraft.class_1642.method_6121(class_1642.java:347)
	at net.minecraft.class_1366.method_6288(class_1366.java:152)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_1396.method_6268(class_1396.java:28)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:774)
	at net.minecraft.class_1309.method_6007(class_1309.java:2664)
	at net.minecraft.class_1308.method_6007(class_1308.java:552)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1642.method_6007(class_1642.java:262)
	at net.minecraft.class_1309.method_5773(class_1309.java:2404)
	at net.minecraft.class_1308.method_5773(class_1308.java:352)
	at net.minecraft.class_1642.method_5773(class_1642.java:235)
	at net.minecraft.class_3218.method_18762(class_3218.java:728)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1642.handler$zgi000$onKilledOther(class_1642.java:708)
	at net.minecraft.class_1642.method_5874(class_1642.java)
	at net.minecraft.class_1309.method_6078(class_1309.java:1352)
	at net.minecraft.class_3988.method_6078(class_3988.java:203)
	at net.minecraft.class_1646.method_6078(class_1646.java:657)
	at net.minecraft.class_1309.method_5643(class_1309.java:1210)
	at net.minecraft.class_1308.method_6121(class_1308.java:1457)
	at net.minecraft.class_1642.method_6121(class_1642.java:347)
	at net.minecraft.class_1366.method_6288(class_1366.java:152)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_1396.method_6268(class_1396.java:28)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:774)
	at net.minecraft.class_1309.method_6007(class_1309.java:2664)
	at net.minecraft.class_1308.method_6007(class_1308.java:552)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1642.method_6007(class_1642.java:262)
	at net.minecraft.class_1309.method_5773(class_1309.java:2404)
	at net.minecraft.class_1308.method_5773(class_1308.java:352)
	at net.minecraft.class_1642.method_5773(class_1642.java:235)
	at net.minecraft.class_3218.method_18762(class_3218.java:728)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.class_1642)
	Entity ID: 2882
	Entity Name: Zombie
	Entity's Exact location: 52.75, 53.02, -3472.23
	Entity's Block location: World: (52,53,-3473), Section: (at 4,5,15 in 3,3,-218; chunk contains blocks 48,-64,-3488 to 63,319,-3473), Region: (0,-7; contains chunks 0,-224 to 31,-193, blocks 0,-64,-3584 to 511,319,-3073)
	Entity's Momentum: -0.03, -0.23, 0.02
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by DrProid** [comment]
Some additional info that might be useful:
Fabric loader version: 0.14.11

Mods:
fabric-api-0.69.0+1.19.3
villagerconverting-1.0.2+1.19
essential_commands-0.30.1-mc1.19.3

**Comment by DrProid** [comment]
In my un-updated server folder I see that I was running fabric-api-0.59.0+1.19.2. So I will run a few more tests.

With Fabric 0.14.9 (1.19.2) and **fabric-api-0.69.0+1.19.2.jar** and villagerconverting-1.0.1+1.19 (I was using 1.0.1 before). No issues.
Followed that up with a test using villagerconverting-1.0.2+1.19. Still no issues in 1.19.2.

**Comment by DrProid** [comment]
Decided to dig into this a little further. I've never modded minecraft before but I had a go at building this mod from your source. Ran `gradlew migrateMappings --mappings "1.19.3+build.3"` and updated gradle.propeties

I got this error:
```...\mc-fabric-villager-converting-main\src\main\java\me\roundaround\villagerconverting\mixin\ZombieEntityMixin.java:57: error: cannot find symbol
    zombieVillagerEntity.setGossipData(villagerEntity.getGossip().serialize(NbtOps.INSTANCE).getValue());
                                                                                            ^
  symbol:   method getValue()
  location: interface NbtElement```
  
 When I commented out that line I got a successful build. Tested it in 1.19.3 and it didn't crash. Obviously though the Gossips data is important. I don't know how to fix that line to be of any more help. But I'll keep digging around and see what turns up.

**Comment by DrProid** [comment]
I made a working build for 1.19.3 by replacing `.getValue()` with `.copy()`. It seems to return the same type so I assume that is fine?

**Comment by Roundaround** [comment]
Sorry you went through all this trouble! I had been putting off updating this (along with a bunch of my other mods) because 1. not many people have made the jump to 1.19.3 and 2. this depends on my library mod, which has a bit of a heftier update path. I'm working on it now though so keep an eye out for it later today!

**Comment by DrProid** [comment]
No need to be sorry. I had fun digging around and learning. Also, I totally understand that there was no need to upgrade to 1.19.3. I was actually hoping there were some cool snapshot features being implemented but seems like they are more likely coming in 1.20.
